# Generated by Django 6.0.4 on 2026-04-14 02:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQRStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qrcode_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('total_scans', models.PositiveIntegerField(default=0)),
                ('unique_scans', models.PositiveIntegerField(default=0)),
                ('mobile_scans', models.PositiveIntegerField(default=0)),
                ('desktop_scans', models.PositiveIntegerField(default=0)),
                ('tablet_scans', models.PositiveIntegerField(default=0)),
                ('country_breakdown', models.JSONField(default=dict)),
                ('browser_breakdown', models.JSONField(default=dict)),
                ('os_breakdown', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'analytics_daily_qr_stats',
                'indexes': [models.Index(fields=['qrcode_id', 'date'], name='analytics_d_qrcode__a355e1_idx'), models.Index(fields=['user_id', 'date'], name='analytics_d_user_id_938fce_idx'), models.Index(fields=['date'], name='analytics_d_date_4a3de6_idx')],
                'unique_together': {('qrcode_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GeoStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode_id', models.UUIDField(db_index=True)),
                ('country_code', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('scans', models.PositiveIntegerField(default=0)),
                ('last_scan_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'analytics_geo_stats',
                'indexes': [models.Index(fields=['qrcode_id'], name='analytics_g_qrcode__54efd5_idx'), models.Index(fields=['country_code'], name='analytics_g_country_e8c7ca_idx')],
                'unique_together': {('qrcode_id', 'country_code', 'city')},
            },
        ),
        migrations.CreateModel(
            name='HourlyQRStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qrcode_id', models.UUIDField(db_index=True)),
                ('date', models.DateField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('scans', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'analytics_hourly_qr_stats',
                'indexes': [models.Index(fields=['qrcode_id', 'date'], name='analytics_h_qrcode__38b5cc_idx')],
                'unique_together': {('qrcode_id', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='UserDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('total_scans', models.PositiveIntegerField(default=0)),
                ('unique_scans', models.PositiveIntegerField(default=0)),
                ('active_qr_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'analytics_user_daily_stats',
                'indexes': [models.Index(fields=['user_id', 'date'], name='analytics_u_user_id_57236a_idx')],
                'unique_together': {('user_id', 'date')},
            },
        ),
    ]
