# Generated by Django 6.0.4 on 2026-04-14 02:24

import apps.qrcodes.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('color', models.CharField(default='#6366F1', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qrcodes_campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('qr_type', models.CharField(choices=[('url', 'URL'), ('dynamic', 'Dynamic URL'), ('whatsapp', 'WhatsApp'), ('vcard', 'vCard / Contact'), ('wifi', 'WiFi'), ('text', 'Plain Text'), ('email', 'Email'), ('sms', 'SMS')], default='url', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('content', models.TextField()),
                ('destination_url', models.URLField(blank=True, max_length=2000)),
                ('foreground_color', models.CharField(default='#000000', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('dot_style', models.CharField(choices=[('square', 'Square'), ('rounded', 'Rounded'), ('dots', 'Dots'), ('classy', 'Classy'), ('classy_rounded', 'Classy Rounded'), ('extra_rounded', 'Extra Rounded')], default='square', max_length=20)),
                ('corner_style', models.CharField(choices=[('square', 'Square'), ('dot', 'Dot'), ('extra_rounded', 'Extra Rounded')], default='square', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.qrcodes.models.qr_logo_path)),
                ('logo_size_ratio', models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('frame_text', models.CharField(blank=True, default='', max_length=50)),
                ('frame_color', models.CharField(default='#000000', max_length=7)),
                ('error_correction', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('Q', 'Quartile'), ('H', 'High')], default='M', max_length=1)),
                ('qr_size', models.PositiveIntegerField(default=300)),
                ('image_png', models.ImageField(blank=True, null=True, upload_to=apps.qrcodes.models.qr_image_path)),
                ('image_svg', models.TextField(blank=True)),
                ('image_pdf', models.FileField(blank=True, null=True, upload_to=apps.qrcodes.models.qr_image_path)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scan_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('is_password_protected', models.BooleanField(default=False)),
                ('access_password_hash', models.CharField(blank=True, max_length=128)),
                ('total_scans', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('unique_scans', models.PositiveBigIntegerField(default=0)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qrcodes', to='qrcodes.qrcodecampaign')),
            ],
            options={
                'db_table': 'qrcodes_qrcode',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRScanEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent_raw', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('os_family', models.CharField(blank=True, max_length=50)),
                ('browser_family', models.CharField(blank=True, max_length=50)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('is_unique', models.BooleanField(default=False)),
                ('referer', models.URLField(blank=True, max_length=2000)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='qrcodes.qrcode')),
            ],
            options={
                'db_table': 'qrcodes_scan_event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='qrcodecampaign',
            index=models.Index(fields=['user', 'is_active'], name='qrcodes_cam_user_id_b1f563_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['user', 'status'], name='qrcodes_qrc_user_id_1671eb_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['user', 'qr_type'], name='qrcodes_qrc_user_id_7742ad_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['short_code'], name='qrcodes_qrc_short_c_49fa76_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['created_at'], name='qrcodes_qrc_created_aeec74_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscanevent',
            index=models.Index(fields=['qrcode', 'timestamp'], name='qrcodes_sca_qrcode__2b0b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscanevent',
            index=models.Index(fields=['qrcode', 'country_code'], name='qrcodes_sca_qrcode__6d1a75_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscanevent',
            index=models.Index(fields=['qrcode', 'device_type'], name='qrcodes_sca_qrcode__2c2578_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscanevent',
            index=models.Index(fields=['fingerprint'], name='qrcodes_sca_fingerp_c1ba29_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscanevent',
            index=models.Index(fields=['is_processed'], name='qrcodes_sca_is_proc_807e71_idx'),
        ),
    ]
