# Generated by Django 6.0.4 on 2026-05-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='outer_shape',
            field=models.CharField(choices=[('square', 'Square'), ('rounded', 'Rounded Square'), ('circle', 'Circle'), ('capsule', 'Capsule'), ('ticket', 'Ticket'), ('apple', 'Apple'), ('duck', 'Duck'), ('shield', 'Shield'), ('blob', 'Blob')], default='square', max_length=20),
        ),
    ]
