# Generated by Django 6.0.4 on 2026-05-03 01:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0003_qrcode_utm_and_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRHealthCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('ok', 'OK'), ('warning', 'Warning'), ('broken', 'Broken')], default='unknown', max_length=20)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_url', models.URLField(blank=True, max_length=2000)),
                ('response_ms', models.PositiveIntegerField(default=0)),
                ('is_safe', models.BooleanField(default=True)),
                ('issue', models.TextField(blank=True)),
                ('qrcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_check', to='qrcodes.qrcode')),
            ],
            options={
                'db_table': 'qrcodes_health_check',
            },
        ),
        migrations.CreateModel(
            name='QRLandingPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('landing', 'Landing Page'), ('menu', 'Menu'), ('review', 'Review'), ('vcard', 'vCard'), ('file', 'File')], default='landing', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('primary_label', models.CharField(default='Open', max_length=80)),
                ('primary_url', models.URLField(blank=True, max_length=2000)),
                ('items', models.JSONField(blank=True, default=list)),
                ('published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qrcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing_page', to='qrcodes.qrcode')),
            ],
            options={
                'db_table': 'qrcodes_landing_page',
            },
        ),
        migrations.CreateModel(
            name='QRConversionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_events', to='qrcodes.qrcode')),
            ],
            options={
                'db_table': 'qrcodes_conversion_event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['qrcode', 'event_type', 'timestamp'], name='qrcodes_con_qrcode__e30cac_idx')],
            },
        ),
        migrations.CreateModel(
            name='QRDestinationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('rule_type', models.CharField(choices=[('device', 'Device'), ('language', 'Language'), ('country', 'Country'), ('time', 'Time Window'), ('ab', 'A/B Test')], default='device', max_length=20)),
                ('match_value', models.CharField(blank=True, help_text='Examples: mobile, en, US, 09:00-17:00. A/B rules can leave this blank.', max_length=120)),
                ('destination_url', models.URLField(max_length=2000)),
                ('weight', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('hits', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_rules', to='qrcodes.qrcode')),
            ],
            options={
                'db_table': 'qrcodes_destination_rule',
                'ordering': ['rule_type', 'name'],
                'indexes': [models.Index(fields=['qrcode', 'rule_type', 'is_active'], name='qrcodes_des_qrcode__f9535d_idx')],
            },
        ),
    ]
