# Generated by Codex on 2026-05-26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("qrcodes", "0004_qrhealthcheck_qrlandingpage_qrconversionevent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRSuspiciousReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("scanned_value", models.TextField()),
                ("normalized_url", models.URLField(blank=True, max_length=2000)),
                ("host", models.CharField(blank=True, db_index=True, max_length=255)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("risk_level", models.CharField(db_index=True, default="unknown", max_length=20)),
                ("safety_snapshot", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent_raw", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("open", "Open"), ("reviewing", "Reviewing"), ("resolved", "Resolved"), ("dismissed", "Dismissed")], db_index=True, default="open", max_length=20)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("reporter", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="qr_reports", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "qrcodes_suspicious_report",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["host", "status"], name="qrcodes_sus_host_7c2b3d_idx"),
                    models.Index(fields=["risk_level", "created_at"], name="qrcodes_sus_risk_le_4f1646_idx"),
                ],
            },
        ),
    ]
