# Generated by Django 6.0.4 on 2026-05-26 01:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0005_qrsuspiciousreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRScannerHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_content', models.TextField()),
                ('content_type', models.CharField(db_index=True, max_length=20)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('risk_level', models.CharField(choices=[('safe', 'Safe'), ('caution', 'Caution'), ('risky', 'Risky')], db_index=True, max_length=20)),
                ('scanned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qrcodes_scanner_history',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['user', 'scanned_at'], name='qrcodes_sca_user_id_fa110d_idx'), models.Index(fields=['user', 'risk_level', 'scanned_at'], name='qrcodes_sca_user_id_b63393_idx')],
            },
        ),
    ]
