# Generated by Django 6.0.4 on 2026-05-26 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_existing_report_reasons(apps, schema_editor):
    QRSuspiciousReport = apps.get_model("qrcodes", "QRSuspiciousReport")
    allowed_reasons = {
        "phishing",
        "fake_payment",
        "wrong_business",
        "malware",
        "spam",
        "other",
        "",
    }
    for report in QRSuspiciousReport.objects.exclude(reason__in=allowed_reasons).iterator():
        old_reason = report.reason or ""
        if old_reason and not report.comment:
            report.comment = old_reason[:1000]
        report.reason = "other"
        report.save(update_fields=["reason", "comment"])


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0006_qrscannerhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodecampaign',
            name='risk_status',
            field=models.CharField(choices=[('clear', 'Clear'), ('watch', 'Watch'), ('elevated', 'Elevated'), ('high', 'High')], db_index=True, default='clear', max_length=20),
        ),
        migrations.AddField(
            model_name='qrcodecampaign',
            name='suspicious_report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qrsuspiciousreport',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qrsuspiciousreport',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_reports', to='qrcodes.qrcodecampaign'),
        ),
        migrations.AddField(
            model_name='qrsuspiciousreport',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qrsuspiciousreport',
            name='qrcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_reports', to='qrcodes.qrcode'),
        ),
        migrations.AddField(
            model_name='qrsuspiciousreport',
            name='reported_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='qrsuspiciousreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(normalize_existing_report_reasons, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='qrsuspiciousreport',
            name='reason',
            field=models.CharField(choices=[('phishing', 'Phishing'), ('fake_payment', 'Fake payment QR'), ('wrong_business', 'Wrong business'), ('malware', 'Malware/download'), ('spam', 'Spam'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
        migrations.AddIndex(
            model_name='qrsuspiciousreport',
            index=models.Index(fields=['qrcode', 'status'], name='qrcodes_sus_qrcode__71eb09_idx'),
        ),
        migrations.AddIndex(
            model_name='qrsuspiciousreport',
            index=models.Index(fields=['campaign', 'status'], name='qrcodes_sus_campaig_b12143_idx'),
        ),
        migrations.AddIndex(
            model_name='qrsuspiciousreport',
            index=models.Index(fields=['reason', 'created_at'], name='qrcodes_sus_reason_132a83_idx'),
        ),
    ]
