# Generated by Django 6.0.4 on 2026-05-26 03:07

import apps.qrcodes.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0007_qrcodecampaign_risk_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=180)),
                ('title', models.CharField(max_length=220)),
                ('issuer', models.CharField(max_length=220)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_id', models.CharField(max_length=120)),
                ('verification_code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='valid', max_length=20)),
                ('pdf_url', models.FileField(blank=True, null=True, upload_to=apps.qrcodes.models.certificate_pdf_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('qrcode', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', to='qrcodes.qrcode')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qrcodes_certificate',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status', 'created_at'], name='qrcodes_cer_workspa_9a9204_idx'), models.Index(fields=['verification_code'], name='qrcodes_cer_verific_2d9831_idx'), models.Index(fields=['certificate_id'], name='qrcodes_cer_certifi_0e9499_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'certificate_id'), name='unique_certificate_id_per_workspace')],
            },
        ),
    ]
