# Generated by Django 6.0.4 on 2026-05-11 17:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def copy_role_to_plan(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="pro").update(plan="pro")
    User.objects.filter(role="enterprise").update(plan="enterprise")
    User.objects.filter(role="admin").update(plan="enterprise")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(db_index=True, default='free', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(copy_role_to_plan, migrations.RunPython.noop),
        migrations.CreateModel(
            name='MembershipOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_code', models.CharField(db_index=True, max_length=30)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=20)),
                ('amount_paise', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('provider', models.CharField(default='paytm', max_length=30)),
                ('provider_order_id', models.CharField(db_index=True, max_length=80, unique=True)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('provider_signature', models.CharField(blank=True, max_length=256)),
                ('receipt', models.CharField(max_length=40, unique=True)),
                ('membership_started_at', models.DateTimeField(blank=True, null=True)),
                ('membership_expires_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_membership_order',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_me_user_id_47002e_idx'), models.Index(fields=['plan_code', 'billing_cycle'], name='accounts_me_plan_co_29be0d_idx')],
            },
        ),
    ]
