# Generated by Django 6.0.4 on 2026-05-26 02:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_google_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Failed Login'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('email_verify', 'Email Verified'), ('api_key_create', 'API Key Created'), ('api_key_revoke', 'API Key Revoked'), ('qr_create', 'QR Created'), ('qr_update', 'QR Updated'), ('qr_delete', 'QR Deleted'), ('profile_update', 'Profile Updated'), ('business_verify', 'Business Verification'), ('business_revoke', 'Business Verification Revoked')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='BusinessVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=160)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('method', models.CharField(choices=[('dns', 'DNS TXT record'), ('html_file', 'HTML file upload'), ('meta_tag', 'Meta tag')], default='dns', max_length=20)),
                ('verification_token', models.CharField(blank=True, db_index=True, max_length=96, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.CASCADE, related_name='business_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_business_verification',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessVerificationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('dns', 'DNS TXT record'), ('html_file', 'HTML file upload'), ('meta_tag', 'Meta tag')], max_length=20)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_attempts', to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='accounts.businessverification')),
            ],
            options={
                'db_table': 'accounts_business_verification_attempt',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='businessverification',
            index=models.Index(fields=['workspace', 'status'], name='accounts_bu_workspa_de3d12_idx'),
        ),
        migrations.AddIndex(
            model_name='businessverification',
            index=models.Index(fields=['domain', 'status'], name='accounts_bu_domain_3c891b_idx'),
        ),
        migrations.AddIndex(
            model_name='businessverificationattempt',
            index=models.Index(fields=['verification', 'checked_at'], name='accounts_bu_verific_abeb7b_idx'),
        ),
        migrations.AddIndex(
            model_name='businessverificationattempt',
            index=models.Index(fields=['success', 'checked_at'], name='accounts_bu_success_afcd80_idx'),
        ),
    ]
