# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_auditlog_action_businessverification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershiporder",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
    ]
