# Generated by Django 6.0.4 on 2026-04-14 02:24

import apps.barcodes.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkBarcodeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('barcode_format', models.CharField(choices=[('code128', 'Code 128'), ('code39', 'Code 39'), ('ean13', 'EAN-13'), ('ean8', 'EAN-8'), ('upca', 'UPC-A'), ('upce', 'UPC-E'), ('itf', 'ITF / Interleaved 2 of 5'), ('gs1_128', 'GS1-128')], max_length=20)),
                ('source_file', models.FileField(upload_to='bulk_jobs/csv/')),
                ('output_zip', models.FileField(blank=True, null=True, upload_to='bulk_jobs/output/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_log', models.JSONField(default=list)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_barcode_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'barcodes_bulk_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('barcode_format', models.CharField(choices=[('code128', 'Code 128'), ('code39', 'Code 39'), ('ean13', 'EAN-13'), ('ean8', 'EAN-8'), ('upca', 'UPC-A'), ('upce', 'UPC-E'), ('itf', 'ITF / Interleaved 2 of 5'), ('gs1_128', 'GS1-128')], default='code128', max_length=20)),
                ('content', models.CharField(max_length=1000)),
                ('foreground_color', models.CharField(default='#000000', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('show_text', models.BooleanField(default=True)),
                ('width', models.PositiveIntegerField(default=300)),
                ('height', models.PositiveIntegerField(default=100)),
                ('font_size', models.PositiveIntegerField(default=10)),
                ('image_png', models.ImageField(blank=True, null=True, upload_to=apps.barcodes.models.barcode_image_path)),
                ('image_svg', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to=settings.AUTH_USER_MODEL)),
                ('bulk_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcodes', to='barcodes.bulkbarcodejob')),
            ],
            options={
                'db_table': 'barcodes_barcode',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'barcode_format'], name='barcodes_ba_user_id_b69c8f_idx'), models.Index(fields=['created_at'], name='barcodes_ba_created_62cad1_idx')],
            },
        ),
    ]
